### ISSUE TITLE
Strange error involving 'never'

### ISSUE THREAD

**Issue by mellis481** [dgreene1/merge-partially#100]
I have an interface with properties of arrays of various types.  Eg:
```
export interface IObject {
  ids: number[];
  types: string[];
```
If I use merge partially like this:
```ts
export const makeFakeObj = (override?: NestedPartial<MyObj>): MyObj => {
  return mergePartially.deep(
    {
      ids: [],
      types: ["test"],
    },
    override
  );
};

```
I'm seeing errors referencing the array props: 
```
Types of property 'types' are incompatible.
      Type '_DeepPartialArray<string> | undefined' is not assignable to type '_DeepPartialArray<never> | undefined'.
        Type '_DeepPartialArray<string>' is not assignable to type '_DeepPartialArray<never>'.
          Type 'string' is not assignable to type 'never'.ts(2345)
```

**Comment by dgreene1** [comment]
@mellis481 there was an issue with the type parameters that made errors like this more confusing. I'm preparing a fix/PR that will produce a TypeScript error that is more clear. This is what you'll see after the new code is deployed.

```
Argument of type '_DeepPartialObject<IObject> | undefined' is not assignable to parameter of type '_DeepPartialObject<{ ids: never[]; types: string[]; }> | undefined'.
  Type '_DeepPartialObject<IObject>' is not assignable to type '_DeepPartialObject<{ ids: never[]; types: string[]; }>'.
    Types of property 'ids' are incompatible.
      Type '_DeepPartialArray<number> | undefined' is not assignable to type '_DeepPartialArray<never> | undefined'.
        Type '_DeepPartialArray<number>' is not assignable to type '_DeepPartialArray<never>'.
          Type 'number' is not assignable to type 'never'.ts(2345)
```

I mean it's more verbose, but it demonstrates the real issue. That's because mergePartially infers the generic type just like all Typescript generic functions. That's why the solutions (describe below) all involve explicitly passing in the interface so that inference doesn't occur.

So even though you wanted the interface to be `IObject`, you can see in the error chain that Typescript inferred it to be:
```ts
{
    ids: never[];
    types: string[];
}
```

That's why the error chain is basically saying that `override.seed`'s ids (which are `string[] | undefined` can not be `never[]`).

**The Solutions**
Either
1) initialize the seed variable with an explicit type before hand

```ts
export const makeFakeObj = (override?: NestedPartial<MyObj>): MyObj => {
  const seed: MyObj = {
      ids: [],
      types: ["test"],
  };
  return mergePartially.deep(
    seed,
    override
  );
};
```

2) add the type parameter to `.deep` like this

```ts
export const makeFakeObj = (override?: NestedPartial<MyObj>): MyObj => {
  return mergePartially.deep<MyObj>(
    {
      ids: [],
      types: ["test"],
    },
    override
  );
};
```
