### ISSUE TITLE
incorrect behaviour with null

### ISSUE THREAD

**Issue by EvgenBabenko** [dgreene1/merge-partially#189]
Hi, can the library work with null?

```typescript
interface IUser {
  id: number;
  firstName: string;
  lastName: string | null;
  age: number;
}

function makeFakeUser(overrides?: NestedPartial<IUser>): IUser {
  return mergePartially.deep(
    {
      id: 1,
      age: 42,
      firstName: 'John',
      lastName: 'Smith',
    },
    overrides,
  );
}
```

I've got the error on overrides: 
```
Argument of type '_DeepPartialObject<IUser> | undefined' is not assignable to parameter of type '_DeepPartialObject<{ id: number; age: number; firstName: string; lastName: string; }> | undefined'.
  Type '_DeepPartialObject<IUser>' is not assignable to type '_DeepPartialObject<{ id: number; age: number; firstName: string; lastName: string; }>'.
    Types of property 'lastName' are incompatible.
      Type 'string | null | undefined' is not assignable to type 'string | undefined'.
        Type 'null' is not assignable to type 'string | undefined'.ts(2345)
```

**Comment by dgreene1** [comment]
Hi @EvgenBabenko. Thank you for using the `merge-partially` library. So yes, the library does support null. There are [multiple unit test cases](https://github.com/dgreene1/merge-partially/blob/a0283b0c2cb9900db52487c4f2926e4cafdc800f/src/index.spec.ts#L52) that use null.

Anyway, I believe the source of your issue is that you're using implicit typing. So if you change `mergePartially.deep` to be `mergePartially.deep<IUser>` then I think it will work for you.

I'm going to close the issue, but please write back if this doesn't solve the problem for you. If it doesn't resolve it, I'll reopen the issue and write a specific test case for your example.
